cst8256/lab02/Lab2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Lab2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

cst8256/lab02/Lab2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lab2.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

cst8256/lab02/Lab2/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lab2.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

cst8256/lab02/Lab2/Pages/Registration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AcademicManagement;

namespace Lab2.Pages
{
    public class RegistrationModel : PageModel
    {
        // binding properties
        [BindProperty]
        public string SelectedStudent { get; set; } = "-1";
        [BindProperty]
        public List<SelectListItem> CourseSelections { get; set; }
        [BindProperty]
        public string RegistrationStatus { get; set; }

        public void OnGet()
        {
        }

        public void OnPostStudentSelected()
        {
            // show student registration status
            if (SelectedStudent != "-1")
            {
                if (DataAccess.GetAcademicRecordsByStudentId(SelectedStudent).Count() == 0)
                {
                    RegistrationStatus = "This student has not registered any courses yet. Select the course(s) below to register.";
                } else
                {
                    RegistrationStatus = $"This student has registered {DataAccess.GetAcademicRecordsByStudentId(SelectedStudent).Count()} course(s): ";
                }
            } else
            {
                RegistrationStatus = "Please select student to view courses.";
            }
        }

        public void OnPostRegister()
        {
            int courseCounter = 0;
            foreach (SelectListItem item in CourseSelections)
            {
                if (item.Selected)
                {
                    AcademicRecord academicRecord = new AcademicRecord(SelectedStudent, item.Value);
                    DataAccess.AddAcademicRecord(academicRecord);
                    courseCounter++;
                }
            }

            if (courseCounter == 0) { RegistrationStatus = "Please select at least 1 (one) course!"; }
            else { RegistrationStatus = "This student has registered the following course(s): "; }
        }
    }
}

cst8256/lab02/Lab2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Registration Management System</h1>
    <p>Select top menu Registration to register students for courses.</p>
</div>

cst8256/lab02/Lab2/Pages/Registration.cshtml
@page
@model Lab2.Pages.RegistrationModel
@using AcademicManagement
@{
	ViewData["Title"] = "Registrations";
	SelectList Options = new SelectList(AcademicManagement.DataAccess.GetAllStudents(), "StudentId", "StudentName");

	Model.CourseSelections = new List<SelectListItem>(); 
    foreach (Course course in AcademicManagement.DataAccess.GetAllCourses())
    {
        Model.CourseSelections.Add(new SelectListItem(course.CourseTitle, course.CourseCode, false));
    }
}

<h1>Registrations</h1>
<hr />

<form method="post">
	<div class="row">
		<!-- Get student info -->
		<div class="col-md-3">
			<select asp-for="SelectedStudent" asp-items="Options" class="form-control">
				<option value="-1">Choose a student. . . </option>
			</select>
		</div>
		<div class="col-md-5">
            <button type="submit" class="btn btn-primary" asp-page-handler="StudentSelected">Get Registration</button>
	    </div>
		<div class="col-md-8 alert-light">@Model.RegistrationStatus</div>
	</div>

	<!-- Course registration info -->
	@if (@Model.SelectedStudent != "-1")
	{
		<!-- If student has registered any courses yet -->
		@if (DataAccess.GetAcademicRecordsByStudentId(@Model.SelectedStudent).Count() > 0)
		{
			<table class="table">
				<thead><tr>
					<th class="control-label">Course Code</th>
					<th class="control-label">Course Title</th>
				</tr></thead>
				<tbody>
					@foreach (AcademicRecord item in DataAccess.GetAcademicRecordsByStudentId(@Model.SelectedStudent))
					{
						<tr><td>@item.CourseCode</td>
						@{
							foreach (Course course in DataAccess.GetAllCourses())
							{
								if (course.CourseCode == item.CourseCode)
								{
									<td>@course.CourseTitle</td>
								}
							}
						}
						</tr>
					}
				</tbody>
			</table>
		} else
		{
			<!-- If student has not registered courses -->
			<table class="table">
				<thead><tr>
					<th>Course Code</th>
					<th>Course Title</th>
					<th>Check to Register</th>
				</tr></thead>
				<tbody>
					@for (int i = 0; i < Model.CourseSelections.Count(); i++)
					{
						<tr>
							<td><input type="hidden" asp-for="@Model.CourseSelections[i].Value" /> @Model.CourseSelections[i].Value </td>
							<td><input type="hidden" asp-for="@Model.CourseSelections[i].Text" /> @Model.CourseSelections[i].Text </td>
							<td><input asp-for="@Model.CourseSelections[i].Selected" /> </td>
						</tr>
					}
				</tbody>
			</table>

			<br />
			<!-- Submit -->
			<button type="submit" class="btn btn-primary" asp-page-handler="Register">Register</button>
		}
	} 
</form>

cst8256/lab02/Lab2/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Lab2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Registration">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lab2 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>